html
  head
    title:[Hello World]
  body
    div:[Hi baby]
      span{id:"black", onclick:"hi()", class:"hello", required}:[kkfkfkfkfk ]
      i{class:"dsld", name:"jkjkj"}:[hellelele]
      select
      form
        fieldset
          input
      		input
      		input
      form
        fieldset
          input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset
      		input
      		input
      		input
      form
      	fieldset